### ISSUE TITLE
Product names instead of Competitor [X]

### ISSUE THREAD

**Issue by mnikolovski** [Arction/javascript-charts-performance-comparison#1]
Hi there,

Can you change the competitor [X] labeling with the product that were compared against?

Thank you.

**Comment by niiloArction** [comment]
Hi,

I'm sorry, but we have intentionally decided to keep all competitor benchmark results unidentified. This is simply an action to protect us from being accused of publicly slandering our competitors.

To compare performance between identified competitors, you'll have to run the benchmarks on your side.
However, it is in our best intention to make this as easy for you as possible. You can find some instructions [here](https://github.com/Arction/javascript-charts-performance-comparison/blob/main/bench/README.md).

Please feel free to ask here any questions or troubles you might come across while replicating the benchmarks.

**Comment by tombohub** [comment]
How do we run benchmarks and get the results?

**Comment by niiloArction** [comment]
As already mentioned, please see https://github.com/Arction/javascript-charts-performance-comparison/blob/main/bench/README.md
