### ISSUE TITLE
Update SciChart to version 3

### ISSUE THREAD

**Issue by viktorskv** [Arction/javascript-charts-performance-comparison#4]
You need to update to scichart version 3, version 2 is quite out of date

I submitted a PR #3, it’s quite simple changes.  Will someone approve it?

**Comment by niiloArction** [comment]
Hey, we can push the bench code updates to the repository, but updating the benchmarks and results will have to wait since it is a huuuge work. We also need to update 10+ other libraries, run all the tests with every single one of them and then update the results. I'll check out the PR.

**Comment by niiloArction** [comment]
SciChart version is now updated.
